import {Account} from '../interfaces/Account';

export const initialAccounts: Account[] = [
  {codigo: '1', nome: 'Receitas', tipo: 'Receita', aceitaLancamento: 'Não'},
  {
    codigo: '1.1',
    nome: 'Taxa condominial',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.2',
    nome: 'Reserva de dependência',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {codigo: '1.3', nome: 'Multas', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {codigo: '1.4', nome: 'Juros', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {
    codigo: '1.5',
    nome: 'Multa condominial',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {codigo: '1.6', nome: 'Água', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {codigo: '1.7', nome: 'Gás', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {
    codigo: '1.8',
    nome: 'Luz e energia',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.9',
    nome: 'Fundo de reserva',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.10',
    nome: 'Fundo de obras',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.11',
    nome: 'Correção monetária',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.12',
    nome: 'Transferência entre contas',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.13',
    nome: 'Pagamento duplicado',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {codigo: '1.14', nome: 'Cobrança', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {codigo: '1.15', nome: 'Crédito', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {
    codigo: '1.16',
    nome: 'Água mineral',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '1.17',
    nome: 'Estorno taxa de resgate',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {codigo: '1.18', nome: 'Acordo', tipo: 'Receita', aceitaLancamento: 'Sim'},
  {
    codigo: '1.19',
    nome: 'Honorários',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2', nome: 'Despesas', tipo: 'Despesa', aceitaLancamento: 'Não'},
  {
    codigo: '2.1',
    nome: 'Com pessoal',
    tipo: 'Despesa',
    aceitaLancamento: 'Não',
  },
  {codigo: '2.1.1', nome: 'Salário', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.1.2',
    nome: 'Adiantamento salarial',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.3',
    nome: 'Hora extra',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.1.4', nome: 'Férias', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.1.5',
    nome: '13º salário',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.6',
    nome: 'Adiantamento 13º salário',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.7',
    nome: 'Adicional de função',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.8',
    nome: 'Aviso prévio',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.1.9', nome: 'INSS', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {codigo: '2.1.10', nome: 'FGTS', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {codigo: '2.1.11', nome: 'PIS', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.1.12',
    nome: 'Vale refeição',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.13',
    nome: 'Vale transporte',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.14',
    nome: 'Cesta básica',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.1.15',
    nome: 'Acordo trabalhista',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.2', nome: 'Mensais', tipo: 'Despesa', aceitaLancamento: 'Não'},
  {
    codigo: '2.2.1',
    nome: 'Energia elétrica',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.2.2',
    nome: 'Água e esgoto',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.2.3',
    nome: 'Taxa de administração',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.2.4', nome: 'Gás', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.2.5',
    nome: 'Seguro obrigatório',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.2.6', nome: 'Telefone', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.2.7',
    nome: 'Softwares e aplicativos',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.3', nome: 'Manutenção', tipo: 'Despesa', aceitaLancamento: 'Não'},
  {codigo: '2.3.1', nome: 'Elevador', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.3.2',
    nome: 'Limpeza e conservação',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '2.3.3',
    nome: 'Jardinagem',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.4', nome: 'Diversas', tipo: 'Despesa', aceitaLancamento: 'Não'},
  {
    codigo: '2.4.1',
    nome: 'Honorários de advogado',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.4.2', nome: 'Xerox', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {codigo: '2.4.3', nome: 'Correios', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.4.4',
    nome: 'Despesas judiciais',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '2.4.5', nome: 'Multas', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {codigo: '2.4.6', nome: 'Juros', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '2.4.7',
    nome: 'Transferência entre contas',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '3',
    nome: 'Despesas bancárias',
    tipo: 'Despesa',
    aceitaLancamento: 'Não',
  },
  {
    codigo: '3.1',
    nome: 'Registro de boletos',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '3.2',
    nome: 'Processamento de boletos',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '3.3',
    nome: 'Registro e processamento de boletos',
    tipo: 'Despesa',
    aceitaLancamento: 'Sim',
  },
  {codigo: '3.4', nome: 'Resgates', tipo: 'Despesa', aceitaLancamento: 'Sim'},
  {
    codigo: '4',
    nome: 'Outras receitas',
    tipo: 'Receita',
    aceitaLancamento: 'Não',
  },
  {
    codigo: '4.1',
    nome: 'Rendimento de poupança',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
  {
    codigo: '4.2',
    nome: 'Rendimento de investimentos',
    tipo: 'Receita',
    aceitaLancamento: 'Sim',
  },
];
